name: Site Helen - Staging

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect on VM
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.HOST_CONNECTION_STRING }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            mkdir teste